
# Configuration file for AI/ML project

# Data configuration
data:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  batch_size: 32
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Model configuration
model:
  architecture: "resnet50"
  num_classes: 10
  learning_rate: 0.001
  epochs: 100
  checkpoint_dir: "models/checkpoints"

# Training configuration
training:
  device: "auto"  # auto, cpu, cuda
  num_workers: 4
  pin_memory: true
  early_stopping_patience: 10

# Logging configuration
logging:
  level: "INFO"
  log_dir: "logs"
