version: '3.8'

services:
  ai-aver:
    build: .
    container_name: ai-aver-analysis
    volumes:
      - ./evidence:/app/evidence
      - ./reports:/app/reports
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - EVIDENCE_DIR=/app/evidence
      - MODELS_DIR=/app/models
    ports:
      - "8080:8080"
    
  database:
    image: postgres:15
    container_name: ai-aver-db
    environment:
      - POSTGRES_DB=evidence_db
      - POSTGRES_USER=forensics
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine
    container_name: ai-aver-cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
